import type { Pact, DefaultPact } from '@/types/pact';

export const mockPacts: Pact[] = [
  {
    id: 'pact-001',
    status: 'expired',
    title: '条件触发 SushiSwap V3 流动性管理',
    description: 'ETH < $2050 时向 WETH/USDC 0.05% 池子添加 0.0001 ETH + 等值 USDC，价格区间 ±5%；ETH > $2060 时撤出全部仓位。若 USDC 不足先通过 SwapRouter 兑换。',
    createdAt: new Date('2026-03-31T11:36:51'),
    agentName: 'Provisioned Agent',
    strategyName: 'SushiSwap V3 条件流动性策略 (Base)',
    chain: 'BASE_ETH',
    validityDays: 30,
    userPrompt: '我想让你帮我在ETH价值低于2050美金的时候帮我执行一笔约0.0001ETH和对应价值的USDC代币投入Sushiswap v3流动性池子的交易，池子地址 https://www.sushi.com/base/pool/v3/0x57713f776e0b0f65ec116912f834e49805480d2，价格区间采用上下5%，如果ETH价格超过 2060美金时，帮我撤回我的全部持仓位。如果执行时发现USDC不够，你先帮我去兑换。',
    permissions: [
      { type: 'write', scope: 'contract call' },
      { type: 'read', scope: 'wallet' },
    ],
    executionSummary: '条件触发流动性管理：ETH < $2050 时向 SushiSwap V3 (WETH/USDC 0.05% on Base) 添加流动性，ETH > $2060 时撤出。',
    contractOps: [
      { label: 'USDC Approve', description: '授权 NonfungiblePositionManager (0x80C7DD17...) 使用 USDC' },
      { label: 'SushiSwap V3 Mint', description: '向 WETH/USDC 池子 (0x57713f77...) mint 仓位，金额 0.0001 ETH + 等值 USDC，价格区间当前价格 ±5%' },
      { label: 'SushiSwap V3 SwapRouter', description: '若 USDC 不足，先从 SwapRouter (0xFB7eF66a...) 兑换' },
      { label: 'decreaseLiquidity + collect', description: 'ETH > $2060 时撤出全部仓位' },
    ],
    riskControls: [
      { label: '单笔 USD 上限', value: '$500' },
      { label: '24h 滚动上限', value: '$1,000' },
      { label: '链限制', value: '仅限 Base 链上 SushiSwap V3 合约' },
      { label: '滑点容忍', value: '1%' },
    ],
    schedule: '持续监控，无特定时间表，条件触发执行，最长授权 30 天。',
    exitConditions: '手动撤销 OR 30天到期',
    riskRules: [
      { name: 'Sushi LP Contracts Allow', type: 'contract_call', chain: 'BASE_ETH', addresses: ['0x80C7DD17...', '0x57713f77...', '0xFB7eF66a...'], action: 'allow' },
    ],
  },
  {
    id: 'pact-002',
    status: 'pending',
    title: 'ETH 定投策略',
    description: '每周一 9:00 UTC 自动购买 $500 等值的 ETH，使用 Uniswap V3 在 Ethereum 主网执行。',
    createdAt: new Date(Date.now() - 20 * 60 * 1000), // 20 min ago → 40 min remaining
    agentName: 'DCA Agent',
    strategyName: 'ETH Weekly DCA (Ethereum)',
    chain: 'ETH',
    validityDays: 90,
    userPrompt: '帮我设置一个ETH定投计划，每周一买入500美金的ETH，用Uniswap执行，持续3个月。',
    permissions: [
      { type: 'write', scope: 'contract call' },
      { type: 'write', scope: 'transfer' },
      { type: 'read', scope: 'wallet' },
    ],
    executionSummary: '每周一 9:00 UTC 通过 Uniswap V3 购买 $500 ETH，持续 90 天。',
    contractOps: [
      { label: 'USDC Approve', description: '授权 Uniswap Router 使用 USDC' },
      { label: 'Uniswap V3 Swap', description: '将 $500 USDC 兑换为 ETH' },
    ],
    riskControls: [
      { label: '单笔 USD 上限', value: '$500' },
      { label: '周滚动上限', value: '$500' },
      { label: '链限制', value: '仅限 Ethereum 主网' },
      { label: '滑点容忍', value: '0.5%' },
    ],
    schedule: '每周一 9:00 UTC 执行，最长授权 90 天。',
    exitConditions: '手动撤销 OR 90天到期 OR 预算耗尽',
    riskRules: [
      { name: 'Uniswap Router Allow', type: 'contract_call', chain: 'ETH', addresses: ['0xE592427A...'], action: 'allow' },
    ],
  },
  {
    id: 'pact-002b',
    status: 'pending',
    title: 'Base 链 AAVE 自动复投',
    description: '监控 AAVE V3 存款收益，每日自动领取并复投 USDC 收益到 Base 链上最优池。',
    createdAt: new Date(Date.now() - 55 * 60 * 1000), // 55 min ago → 5 min remaining (urgent)
    agentName: 'Yield Optimizer',
    strategyName: 'AAVE V3 Auto-compound (Base)',
    chain: 'BASE_ETH',
    validityDays: 60,
    userPrompt: '帮我把AAVE上Base链的USDC存款收益每天自动复投回去。',
    permissions: [
      { type: 'write', scope: 'contract call' },
      { type: 'read', scope: 'wallet' },
    ],
    executionSummary: '每日检查 AAVE V3 Base 链上的 USDC 收益，自动领取并复投。',
    contractOps: [
      { label: 'Claim Rewards', description: '从 AAVE V3 领取 USDC 收益' },
      { label: 'Re-supply', description: '将收益重新存入 AAVE V3' },
    ],
    riskControls: [
      { label: '单笔 USD 上限', value: '$1,000' },
      { label: '24h 滚动上限', value: '$2,000' },
      { label: '链限制', value: '仅限 Base' },
    ],
    schedule: '每日 00:00 UTC 执行，最长授权 60 天。',
    exitConditions: '手动撤销 OR 60天到期',
    riskRules: [
      { name: 'AAVE V3 Base Allow', type: 'contract_call', chain: 'BASE_ETH', addresses: ['0x794a6135...'], action: 'allow' },
    ],
  },
  {
    id: 'pact-002c',
    status: 'pending',
    title: 'Solana MEV 套利监控',
    description: '在 Solana 链上监控 Jupiter 聚合器的套利机会，自动执行低风险套利交易。',
    createdAt: new Date(Date.now() - 90 * 60 * 1000), // 90 min ago → already expired
    agentName: 'MEV Scout',
    strategyName: 'Jupiter Arb Monitor (Solana)',
    chain: 'SOL',
    validityDays: 7,
    userPrompt: '帮我在Solana上用Jupiter找套利机会，自动执行，控制好风险。',
    permissions: [
      { type: 'write', scope: 'contract call' },
      { type: 'write', scope: 'transfer' },
      { type: 'read', scope: 'wallet' },
    ],
    executionSummary: '持续监控 Jupiter 聚合器套利机会，自动执行低风险交易。',
    contractOps: [
      { label: 'Jupiter Swap', description: '通过 Jupiter 聚合器执行兑换' },
      { label: 'Token Transfer', description: '将利润转回主钱包' },
    ],
    riskControls: [
      { label: '单笔 USD 上限', value: '$200' },
      { label: '24h 滚动上限', value: '$1,000' },
      { label: '最小利润率', value: '0.3%' },
    ],
    schedule: '持续监控，条件触发执行，最长授权 7 天。',
    exitConditions: '手动撤销 OR 7天到期',
    riskRules: [
      { name: 'Jupiter Router Allow', type: 'contract_call', chain: 'SOL', addresses: ['JUP6...'], action: 'allow' },
    ],
  },
  {
    id: 'pact-003',
    status: 'approved',
    title: 'Aave V3 借贷管理',
    description: '当 ETH 价格下跌至清算线 120% 时自动补充抵押品，维持健康因子 > 1.5。',
    createdAt: new Date('2026-03-28T14:20:00'),
    agentName: 'Risk Manager Agent',
    strategyName: 'Aave V3 健康因子守护 (Arbitrum)',
    chain: 'ARB_ETH',
    validityDays: 60,
    userPrompt: '监控我的Aave V3借贷仓位，如果健康因子低于1.5就自动补充ETH抵押品，保持安全。',
    permissions: [
      { type: 'write', scope: 'contract call' },
      { type: 'read', scope: 'wallet' },
    ],
    executionSummary: '监控 Aave V3 健康因子，低于 1.5 时自动补充 ETH 抵押品。',
    contractOps: [
      { label: 'Aave Pool Supply', description: '向 Aave V3 Pool 补充 ETH 抵押品' },
      { label: 'WETH Approve', description: '授权 Aave Pool 使用 WETH' },
    ],
    riskControls: [
      { label: '单笔 USD 上限', value: '$2,000' },
      { label: '24h 滚动上限', value: '$5,000' },
      { label: '链限制', value: '仅限 Arbitrum' },
      { label: '最大补仓次数', value: '每日 3 次' },
    ],
    schedule: '持续监控，条件触发执行，最长授权 60 天。',
    exitConditions: '手动撤销 OR 60天到期',
    riskRules: [
      { name: 'Aave V3 Pool Allow', type: 'contract_call', chain: 'ARB_ETH', addresses: ['0x794a61358B...'], action: 'allow' },
    ],
  },
  {
    id: 'pact-004',
    status: 'rejected',
    title: '跨链套利策略',
    description: '在 Arbitrum 和 Optimism 之间寻找 USDC/USDT 价差套利机会，自动执行跨链交易。',
    createdAt: new Date('2026-03-25T18:45:00'),
    agentName: 'Arb Bot Agent',
    strategyName: '跨链套利 (ARB-OP)',
    chain: 'ARB_ETH',
    validityDays: 14,
    userPrompt: '帮我在Arbitrum和Optimism之间找USDC/USDT的套利机会并自动执行。',
    permissions: [
      { type: 'write', scope: 'contract call' },
      { type: 'write', scope: 'transfer' },
      { type: 'read', scope: 'wallet' },
    ],
    executionSummary: '跨链 USDC/USDT 套利，在 Arbitrum 和 Optimism 间执行。',
    contractOps: [
      { label: 'Bridge Transfer', description: '通过 Stargate 跨链桥转移资产' },
      { label: 'DEX Swap', description: '在目标链上 DEX 执行兑换' },
    ],
    riskControls: [
      { label: '单笔 USD 上限', value: '$10,000' },
      { label: '24h 滚动上限', value: '$50,000' },
      { label: '链限制', value: 'Arbitrum + Optimism' },
      { label: '最小利润', value: '0.1%' },
    ],
    schedule: '持续监控，条件触发执行，最长授权 14 天。',
    exitConditions: '手动撤销 OR 14天到期',
    riskRules: [
      { name: 'Stargate Bridge Allow', type: 'contract_call', chain: 'ARB_ETH', action: 'allow' },
    ],
  },
  {
    id: 'pact-005',
    status: 'active',
    title: 'USDC 收益优化',
    description: '将闲置 USDC 存入收益最高的借贷协议，每日自动复投收益。',
    createdAt: new Date('2026-03-29T10:00:00'),
    agentName: 'Yield Agent',
    strategyName: 'USDC 最优收益 (Base)',
    chain: 'BASE_ETH',
    validityDays: 30,
    userPrompt: '帮我把闲置的USDC存到收益最高的协议里，每天自动复投。',
    permissions: [
      { type: 'write', scope: 'contract call' },
      { type: 'read', scope: 'wallet' },
    ],
    executionSummary: '自动将 USDC 存入 Base 链上收益最高的借贷协议，每日复投。',
    contractOps: [
      { label: 'USDC Approve', description: '授权借贷协议使用 USDC' },
      { label: 'Supply', description: '将 USDC 存入协议' },
      { label: 'Claim & Reinvest', description: '领取并复投收益' },
    ],
    riskControls: [
      { label: '单笔 USD 上限', value: '$5,000' },
      { label: '24h 滚动上限', value: '$10,000' },
      { label: '链限制', value: '仅限 Base' },
      { label: '协议限制', value: '仅限审计过的协议' },
    ],
    schedule: '每日 00:00 UTC 检查收益并复投，最长授权 30 天。',
    exitConditions: '手动撤销 OR 30天到期',
    riskRules: [
      { name: 'Lending Protocol Allow', type: 'contract_call', chain: 'BASE_ETH', action: 'allow' },
    ],
  },
];

export const mockDefaultPacts: DefaultPact[] = [
  {
    id: 'dp-001',
    name: '标准交易限额',
    description: '适用于所有 Agent 的默认交易限额和风控规则',
    enabled: true,
    maxPerTx: 500,
    rolling24h: 1000,
    allowedChains: ['ETH', 'BASE_ETH', 'ARB_ETH'],
    allowedTokens: ['ETH', 'USDC', 'USDT'],
    contractWhitelist: [],
    maxValidityDays: 30,
  },
  {
    id: 'dp-002',
    name: '高级 DeFi 策略',
    description: '适用于 DeFi 策略 Agent 的扩展限额',
    enabled: true,
    maxPerTx: 2000,
    rolling24h: 5000,
    allowedChains: ['ETH', 'BASE_ETH', 'ARB_ETH', 'OP_ETH'],
    allowedTokens: ['ETH', 'WETH', 'USDC', 'USDT', 'DAI'],
    contractWhitelist: ['Uniswap V3', 'Aave V3', 'SushiSwap V3'],
    maxValidityDays: 90,
  },
  {
    id: 'dp-003',
    name: '只读监控',
    description: '仅允许读取钱包数据，不允许任何交易操作',
    enabled: false,
    maxPerTx: 0,
    rolling24h: 0,
    allowedChains: ['ETH', 'BASE_ETH', 'ARB_ETH', 'OP_ETH', 'BSC'],
    allowedTokens: [],
    contractWhitelist: [],
    maxValidityDays: 365,
  },
];
