import type { Message, TodoItem } from '@/types/notification';

// ============================
// Mock Messages
// ============================

export const mockMessages: Message[] = [
  // Transaction — transfer (outgoing, matches tx-day3-2)
  {
    id: 'msg-tx-1',
    category: 'transaction',
    subType: 'transfer',
    title: '转账',
    summary: '接收方 0x6B17...3355',
    amount: '-0.5 ETH',
    status: { label: '成功', variant: 'success' },
    timestamp: new Date(Date.now() - 25 * 60 * 1000),
    isRead: false,
    route: '/transaction/tx-day3-2',
    icon: { type: 'crypto', symbol: 'ETH', chainId: 'ethereum' },
  },
  // Transaction — contract interaction (matches tx-day5-1)
  {
    id: 'msg-tx-2',
    category: 'transaction',
    subType: 'contract_interaction',
    title: '合约交互',
    summary: '合约 0x3fC9...7FAD',
    amount: '-200 USDT',
    status: { label: '成功', variant: 'success' },
    timestamp: new Date(Date.now() - 10 * 60 * 1000),
    isRead: false,
    route: '/transaction/tx-day5-1',
    icon: { type: 'crypto', symbol: 'USDT', chainId: 'ethereum' },
  },
  // Transaction — transfer (incoming, matches tx-day3-1)
  {
    id: 'msg-tx-3',
    category: 'transaction',
    subType: 'transfer',
    title: '收款',
    summary: '发送方 0x3fC9...7FAD',
    amount: '+1,800 USDT',
    status: { label: '成功', variant: 'success' },
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
    isRead: true,
    route: '/transaction/tx-day3-1',
    icon: { type: 'crypto', symbol: 'USDT', chainId: 'ethereum' },
  },
  // Transaction — message signing (matches tx-day4-2)
  {
    id: 'msg-tx-4',
    category: 'transaction',
    subType: 'message_signing',
    title: '消息签名',
    summary: 'OpenSea',
    status: { label: '成功', variant: 'success' },
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    isRead: true,
    route: '/transaction/tx-day4-2',
    icon: { type: 'generic' },
  },
  // Transaction — transfer (failed, matches tx-day6-2)
  {
    id: 'msg-tx-5',
    category: 'transaction',
    subType: 'transfer',
    title: '转账',
    summary: '接收方 0xdAC1...1eC7',
    amount: '-0.001 ETH',
    status: { label: '失败', variant: 'error' },
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000),
    isRead: true,
    route: '/transaction/tx-day6-2',
    icon: { type: 'crypto', symbol: 'ETH', chainId: 'ethereum' },
  },

  // Pact messages — IDs and statuses match mock-pacts.ts
  {
    id: 'msg-pact-1',
    category: 'pact',
    subType: 'pact_activated',
    title: 'Pact',
    summary: '允许 Yield Agent 将闲置 USDC 存入收益最高的借贷协议',
    status: { label: '已批准', variant: 'success' },
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    isRead: false,
    route: '/pact-approval-detail/todo-pact-4',
    icon: { type: 'generic' },
  },
  {
    id: 'msg-pact-2',
    category: 'pact',
    subType: 'pact_rejected',
    title: 'Pact',
    summary: '允许 Arb Bot Agent 在 Arbitrum 和 Optimism 之间执行跨链套利',
    status: { label: '已拒绝', variant: 'error' },
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
    isRead: true,
    route: '/pact/pact-004',
    icon: { type: 'generic' },
  },
  {
    id: 'msg-pact-3',
    category: 'pact',
    subType: 'pact_expired',
    title: 'Pact',
    summary: '允许 Provisioned Agent 执行 SushiSwap V3 条件流动性管理',
    status: { label: '已过期', variant: 'muted' },
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
    isRead: true,
    route: '/pact/pact-001',
    icon: { type: 'generic' },
  },

  // System messages
  {
    id: 'msg-sys-1',
    category: 'system',
    subType: 'backup_reminder',
    title: '钱包尚未备份',
    summary: '建议立即备份以防止资产丢失',
    status: { label: '待处理', variant: 'warning' },
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000),
    isRead: false,
    route: '/wallet-backup/wallet-1',
    icon: { type: 'generic' },
  },
  {
    id: 'msg-sys-2',
    category: 'system',
    subType: 'upgrade_prompt',
    title: '新版本可用 v2.1.0',
    summary: '修复了已知问题，提升了性能',
    status: { label: '更新', variant: 'info' },
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    isRead: true,
    route: '/profile/help',
    icon: { type: 'generic' },
  },
];

// ============================
// Mock Todos
// ============================

export const mockTodoItems: TodoItem[] = [
  // ── Pact approvals ──
  {
    id: 'todo-pact-1',
    type: 'pact_approval',
    title: 'Pact 创建',
    summary: 'ETH 定投策略',
    status: 'pending',
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
    route: '/pact-approval-detail/todo-pact-1',
    metadata: {
      type: 'pact_approval',
      agentName: 'DCA Agent',
      agentId: 'agent-001',
      walletName: 'Trading Wallet',
      pactId: 'pact-002',
      intent: 'ETH 定投策略',
      txType: 'contract_interaction',
    },
  },
  {
    id: 'todo-pact-2',
    type: 'pact_approval',
    title: 'Pact 创建',
    summary: 'Aave V3 借贷管理',
    status: 'approved',
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    completedAt: new Date(Date.now() - 3.5 * 60 * 60 * 1000),
    route: '/pact-approval-detail/todo-pact-2',
    metadata: {
      type: 'pact_approval',
      agentName: 'Risk Manager Agent',
      agentId: 'agent-002',
      walletName: 'Trading Wallet',
      pactId: 'pact-003',
      intent: 'Aave V3 借贷管理',
      txType: 'contract_interaction',
    },
  },
  {
    id: 'todo-pact-3',
    type: 'pact_approval',
    title: 'Pact 创建',
    summary: 'NFT 市场签名授权',
    status: 'pending',
    createdAt: new Date(Date.now() - 45 * 60 * 1000),
    route: '/pact-approval-detail/todo-pact-3',
    metadata: {
      type: 'pact_approval',
      agentName: 'NFT Manager',
      agentId: 'agent-006',
      walletName: 'Trading Wallet',
      pactId: 'pact-006',
      intent: 'NFT 市场签名授权',
      txType: 'message_signing',
    },
  },
  {
    id: 'todo-pact-4',
    type: 'pact_approval',
    title: 'Pact 创建',
    summary: 'USDC 收益优化',
    status: 'rejected',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    completedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000),
    route: '/pact-approval-detail/todo-pact-4',
    metadata: {
      type: 'pact_approval',
      agentName: 'Yield Agent',
      agentId: 'agent-005',
      walletName: 'Trading Wallet',
      pactId: 'pact-005',
      intent: 'USDC 收益优化',
      txType: 'contract_interaction',
    },
  },

  // ── Excess approvals ──
  {
    id: 'todo-excess-1',
    type: 'excess_approval',
    title: 'Pact 交易',
    summary: 'DeFi 套利策略',
    status: 'pending',
    createdAt: new Date(Date.now() - 15 * 60 * 1000),
    route: '/excess-approval/todo-excess-1',
    metadata: {
      type: 'excess_approval',
      txType: 'transfer',
      amount: 5000,
      symbol: 'USDT',
      chainId: 'ethereum',
      toAddress: '0xab12...cd34',
      pactId: 'pact-001',
      pactName: 'DeFi 套利策略',
    },
  },
  {
    id: 'todo-excess-2',
    type: 'excess_approval',
    title: 'Pact 交易',
    summary: 'Aave V3 借贷管理',
    status: 'approved',
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    completedAt: new Date(Date.now() - 2.8 * 60 * 60 * 1000),
    route: '/excess-approval/todo-excess-2',
    metadata: {
      type: 'excess_approval',
      txType: 'contract_interaction',
      amount: 2500,
      symbol: 'ETH',
      chainId: 'arbitrum',
      toAddress: '0x794a...14aD',
      pactId: 'pact-003',
      pactName: 'Aave V3 借贷管理',
    },
  },
  {
    id: 'todo-excess-3',
    type: 'excess_approval',
    title: 'Pact 交易',
    summary: 'USDC 收益优化',
    status: 'rejected',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    completedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000),
    route: '/excess-approval/todo-excess-3',
    metadata: {
      type: 'excess_approval',
      txType: 'contract_interaction',
      amount: 12000,
      symbol: 'USDC',
      chainId: 'base',
      toAddress: '0x18cD...Bfe2',
      pactId: 'pact-005',
      pactName: 'USDC 收益优化',
    },
  },

  // ── TSS signing ──
  {
    id: 'todo-tss-1',
    type: 'tss_signing',
    title: '交易签名',
    summary: '0x7a25...3f8d',
    status: 'pending',
    createdAt: new Date(Date.now() - 5 * 60 * 1000),
    route: '/tss-signing/todo-tss-1',
    metadata: {
      type: 'tss_signing',
      txType: 'transfer',
      amount: 1.5,
      symbol: 'ETH',
      chainId: 'ethereum',
      toAddress: '0x7a25...3f8d',
      txId: 'tx-005',
    },
  },
  {
    id: 'todo-tss-2',
    type: 'tss_signing',
    title: '交易签名',
    summary: '0xdAC1...1eC7',
    status: 'approved',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    completedAt: new Date(Date.now() - 1.8 * 60 * 60 * 1000),
    route: '/tss-signing/todo-tss-2',
    metadata: {
      type: 'tss_signing',
      txType: 'transfer',
      amount: 200,
      symbol: 'USDT',
      chainId: 'ethereum',
      toAddress: '0xdAC1...1eC7',
      txId: 'tx-tss-signed',
    },
  },
  {
    id: 'todo-tss-3',
    type: 'tss_signing',
    title: '交易签名',
    summary: '0x3C44...93E8',
    status: 'failed',
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
    completedAt: new Date(Date.now() - 5.5 * 60 * 60 * 1000),
    route: '/tss-signing/todo-tss-3',
    metadata: {
      type: 'tss_signing',
      txType: 'contract_interaction',
      amount: 800,
      symbol: 'USDC',
      chainId: 'base',
      toAddress: '0x3C44...93E8',
      txId: 'tx-006',
    },
  },
  {
    id: 'todo-tss-4',
    type: 'tss_signing',
    title: '交易签名',
    summary: '0x00000000...14dC',
    status: 'pending',
    createdAt: new Date(Date.now() - 10 * 60 * 1000),
    route: '/tss-signing/todo-tss-4',
    metadata: {
      type: 'tss_signing',
      txType: 'contract_interaction',
      amount: 3200,
      symbol: 'USDC',
      chainId: 'base',
      toAddress: '0x00000000...14dC',
      txId: 'tx-007',
    },
  },
  {
    id: 'todo-tss-5',
    type: 'tss_signing',
    title: '交易签名',
    summary: '0x742d...bD18',
    status: 'pending',
    createdAt: new Date(Date.now() - 20 * 60 * 1000),
    route: '/tss-signing/todo-tss-5',
    metadata: {
      type: 'tss_signing',
      txType: 'message_signing',
      toAddress: '0x742d35Cc6634C0532925a3b844Bc9e7595f2bD18',
      txId: 'tx-008',
      eip712: {
        domain: {
          name: '1inch Aggregation Router',
          version: '6',
          chainId: '0x1',
          verifyingContract: '0x111111125421ca6dc452d289314280a0f8842a65',
        },
        primaryType: 'Order',
        message: {
          salt: '33701747986552662907267395941863510909070357040845548943442782185911632893258',
          maker: '0x20dd6b24f1f9ebf4dbc5a330b0fe708f2b37ebf7',
          receiver: '0xc0dfdb9e7a392c3dbbe7c6fbe8fbc1789c9fe05e',
          makerAsset: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
          takerAsset: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2',
          makingAmount: '2187822972',
          takingAmount: '995960463720588000',
          makerTraits: '35280402189494778293119284494834596924043200600333326411950615168275764477952',
        },
      },
    },
  },
  {
    id: 'todo-tss-6',
    type: 'tss_signing',
    title: '交易签名',
    summary: '0xFB7e...9b9f',
    status: 'approved',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    completedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 3 * 60 * 1000),
    route: '/tss-signing/todo-tss-6',
    metadata: {
      type: 'tss_signing',
      txType: 'contract_interaction',
      amount: 500,
      symbol: 'USDT',
      chainId: 'arbitrum',
      toAddress: '0xFB7e...9b9f',
      txId: 'tx-009',
    },
  },
  {
    id: 'todo-tss-7',
    type: 'tss_signing',
    title: '交易签名',
    summary: '0x53Bf...1614',
    status: 'rejected',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    completedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000),
    route: '/tss-signing/todo-tss-7',
    metadata: {
      type: 'tss_signing',
      txType: 'transfer',
      amount: 10000,
      symbol: 'USDC',
      chainId: 'ethereum',
      toAddress: '0x53Bf...1614',
      txId: 'tx-010',
    },
  },
];
